# fly.toml app configuration file generated for kastara on 2023-12-16T16:44:00+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# PATH="/home/nadib/.fly/bin:$PATH"

app = "kastara"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "20.9.0"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  APP_URL="https://kastara.fly.dev/"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION='mysql'
  DB_HOST='aws.connect.psdb.cloud'
  DB_DATABASE='kastara'
  MYSQL_ATTR_SSL_CA='/etc/ssl/certs/ca-certificates.crt'
  MAIL_MAILER="smtp"
  MAIL_HOST="sandbox.smtp.mailtrap.io"
  MAIL_PORT=2525

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
#  strategy = "bluegreen"
  release_command = "php artisan storage:link && php artisan migrate --force"

[mounts]
  source = "storage_dir"
  destination = "/var/www/html/storage"
